# ------------------------------------------------------------------------------
# Project : PyPlate                                                /          \
# Filename: mkdocs.yml                                            |     ()     |
# Date    : 09/13/2025                                            |            |
# Author  : cyclopticnerve                                        |   \____/   |
# License : WTFPLv2                                                \          /
# ------------------------------------------------------------------------------

site_name: PyPlate
theme: 
docs_dir: docs
site_dir: site
plugins:
    - search
    - mkdocstrings

# -)
