# ------------------------------------------------------------------------------
# Project : __PP_NAME_PRJ_BIG__                                    /          \
# Filename: mkdocs.yml                                            |     ()     |
# Date    : __PP_DATE__                                           |            |
# Author  : __PP_AUTHOR__                                         |   \____/   |
# License : __PP_LICENSE_NAME__                                    \          /
# ------------------------------------------------------------------------------

site_name: __PP_NAME_PRJ__
theme: 
docs_dir: __PP_DIR_DOCS__
site_dir: __PP_DIR_SITE__
plugins:
    - search
    - mkdocstrings

# -)
